on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate JSON Schema
        shell: pwsh
        run: ./helpers/CheckOutdatedVersionPinning.ps1
